
import { Review } from './types';

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1',
    fullName: 'João da Silva',
    academicRegistry: 'RA123456',
    university: 'Universidade Estácio de Sá',
    course: 'Análise e Desenvolvimento de Sistemas',
    campus: 'Polo Copacabana',
    region: 'Sudeste',
    courseQuality: 5,
    professorQuality: 4,
    studySupport: 5,
    onSiteSupport: 4,
    didacticMaterial: 5,
    comment: 'Ótimo curso, material didático super completo e professores atenciosos. O polo de apoio é bem localizado.',
    createdAt: new Date('2023-10-20T10:00:00Z'),
  },
  {
    id: '2',
    fullName: 'Maria Oliveira',
    academicRegistry: 'RA789012',
    university: 'Universidade Cruzeiro do Sul',
    course: 'Pedagogia',
    campus: 'Polo Liberdade',
    region: 'Sudeste',
    courseQuality: 4,
    professorQuality: 4,
    studySupport: 3,
    onSiteSupport: 5,
    didacticMaterial: 4,
    comment: 'A plataforma é um pouco confusa no começo, mas os professores são excelentes e o polo presencial é muito organizado.',
    createdAt: new Date('2023-11-05T14:30:00Z'),
  },
  {
    id: '3',
    fullName: 'Carlos Pereira',
    academicRegistry: 'RA345678',
    university: 'Universidade Estácio de Sá',
    course: 'Análise e Desenvolvimento de Sistemas',
    campus: 'Polo Barra da Tijuca',
    region: 'Sudeste',
    courseQuality: 4,
    professorQuality: 3,
    studySupport: 4,
    onSiteSupport: 3,
    didacticMaterial: 4,
    comment: 'Bom curso, mas alguns professores demoram para responder. O material é bom.',
    createdAt: new Date('2024-01-15T09:00:00Z'),
  },
  {
    id: '4',
    fullName: 'Ana Souza',
    academicRegistry: 'RA901234',
    university: 'Universidade Anhanguera',
    course: 'Administração',
    campus: 'Polo Curitiba',
    region: 'Sul',
    courseQuality: 3,
    professorQuality: 4,
    studySupport: 2,
    onSiteSupport: 4,
    didacticMaterial: 3,
    comment: 'O curso é razoável, mas o suporte ao aluno poderia ser bem melhor. O polo é bom.',
    createdAt: new Date('2024-02-01T18:45:00Z'),
  },
  {
    id: '5',
    fullName: 'Lucas Ferreira',
    academicRegistry: 'RA567890',
    university: 'Universidade Paulista (UNIP)',
    course: 'Ciências Contábeis',
    campus: 'Polo Recife',
    region: 'Nordeste',
    courseQuality: 5,
    professorQuality: 5,
    studySupport: 5,
    onSiteSupport: 5,
    didacticMaterial: 5,
    comment: 'Experiência fantástica! Curso completo, plataforma estável e tutores sempre presentes. Recomendo!',
    createdAt: new Date('2024-03-10T11:20:00Z'),
  },
   {
    id: '6',
    fullName: 'Fernanda Lima',
    academicRegistry: 'RA112233',
    university: 'Universidade Cruzeiro do Sul',
    course: 'Pedagogia',
    campus: 'Polo Salvador',
    region: 'Nordeste',
    courseQuality: 5,
    professorQuality: 5,
    studySupport: 4,
    onSiteSupport: 4,
    didacticMaterial: 5,
    comment: 'Adorei o curso, muito bem estruturado para o EAD.',
    createdAt: new Date('2024-04-22T13:00:00Z'),
  },
];

export const RATING_CRITERIA = {
  courseQuality: 'Qualidade do curso',
  professorQuality: 'Qualidade dos professores',
  studySupport: 'Apoio nos estudos',
  onSiteSupport: 'Polo de apoio presencial',
  didacticMaterial: 'Material didático',
};

export const REGIONS = ['Norte', 'Nordeste', 'Centro-Oeste', 'Sudeste', 'Sul'];
