export const COURSE_CATALOG: { area: string; grau: number; cursos: string[] }[] = [
  {
    "area": "Agricultura, silvicultura, pesca e veterinária",
    "grau": 1.0,
    "cursos": [
      "Agronomia", "Engenharia Florestal", "Medicina Veterinária", "Zootecnia",
      "Engenharia Agrícola", "Engenharia Agronômica", "Engenharia Agrícola E Ambiental",
      "Engenharia De Pesca", "Engenharia De Aquicultura", "Agroecologia", "Agroindústria",
      "Engenharia De Biossistemas", "Desenvolvimento Rural", "Interdisciplinar Em Ciências Agrárias - Bi/Li",
      "Aquacultura", "Enologia", "Desenvolvimento Rural E Gestão Agroindustrial"
    ]
  },
  {
    "area": "Agricultura, silvicultura, pesca e veterinária",
    "grau": 3.0,
    "cursos": [
      "Agroecologia", "Horticultura", "Agroindústria", "Agropecuária", "Produção De Grãos",
      "Produção Agrícola", "Silvicultura", "Produção De Cacau E Chocolate", "Irrigação E Drenagem",
      "Aqüicultura", "Viticultura E Enologia", "Produção Pesqueira", "Cafeicultura",
      "Mecanização Em Agricultura De Precisão", "Produção Agropecuária", "Gestão De Equinocultura", "Fruticultura"
    ]
  },
  {
    "area": "Artes e humanidades",
    "grau": 1.0,
    "cursos": [
      "Artes Cênicas - Interpretação Teatral", "Artes Visuais", "Design - Programação Visual",
      "Design - Projeto Do Produto", "Filosofia", "História", "Letras - Francês",
      "Letras - Língua Inglesa E Respectiva Literatura", "Letras - Língua Portuguesa E Respectiva Literatura",
      "Letras - Tradução Espanhol", "Letras - Tradução Francês", "Letras - Tradução Inglês",
      "Línguas Estrangeiras Aplicadas Ao Multilinguismo E À Sociedade Da Informação", "Música",
      "Música - Composição", "Música - Regência", "Teoria, Crítica E História Da Arte",
      "Letras - Tradutor E Intérprete", "Cinema E Mídias Digitais", "Design Visual",
      "Comunicação Social - Cinema E Mídias Digitais", "Teatro", "Teologia", "Cinema E Audiovisual",
      "Design De Moda", "Design De Produto", "Design Gráfico E Digital", "Direção De Arte",
      "Letras: Estudos Literários", "Letras: Linguística", "Letras: Tradução E Interpretação Em Libras/Português",
      "Música - Canto", "Música - Instrumento Musical", "Música Popular - Canto Popular",
      "Música Popular - Instrumento Musical", "Música Popular - Produção Musical", "Arqueologia", "Design",
      "Música - Cordas Friccionadas", "Música - Sopros", "Música - Violão", "Audiovisual", "Letras",
      "Artes Cênicas", "Design Gráfico", "Interdisciplinar Em Humanidades",
      "Línguas Estrangeiras Aplicadas Às Negociações Internacionais", "Interdisciplinar Em Artes",
      "Produção Cultural", "Artes Do Corpo Em Cena", "Som, Imagem E Movimento", "Canto Lírico",
      "Composição E Regência", "Dança", "Design De Interiores", "Instrumento", "Letras - Língua Estrangeira",
      "Letras Vernáculas", "Música Popular", "Comunicação Social - Cinema E Audiovisual",
      "Interdisciplinar Em Cultura, Linguagens E Tecnologias Aplicadas", "Humanidades - Bi/Li", "Design - Moda",
      "Letras - Inglês", "Letras - Língua Portuguesa", "Música - Flauta Transversal", "Música - Piano",
      "Música Popular - Saxofone", "Moda", "Teologia Pastoral", "Ciências Da Religião", "Arte E Mídia",
      "Ciências Das Religiões", "Comunicação Em Mídias Digitais", "Tradução", "Música - Instrumento",
      "Arqueologia E Preservação Patrimonial", "Moda, Design E Estilismo", "Ciências Teológicas",
      "Conservação E Restauro", "Música - Cordas", "Letras - Libras", "Artes Plásticas",
      "Cinema De Animação E Artes Digitais", "Conservação E Restauração De Bens Culturais Móveis",
      "Design De Ambientes", "Computação Gráfica", "Design De Games", "Música - Música Popular Brasileira",
      "Ciência Da Religião", "Interdisciplinar Em Artes E Design - Bi/Li",
      "Interdisciplinar Em Ciências Humanas - Bi/Li", "Letras - Estudos Literários", "Letras - Tradução",
      "Artes Aplicadas", "Artes", "Desenho Industrial", "Letras - Alemão", "Letras - Grego", "Letras - Italiano",
      "Artes Cênicas - Cenografia", "Artes Cênicas - Direção Teatral", "Artes Cênicas - Indumentária",
      "Artes Visuais - Escultura", "Artes Visuais - Gravura", "Comunicação Visual Design",
      "Conservação E Restauração", "Design Industrial", "História Da Arte", "Letras - Português E Alemão",
      "Letras - Português E Espanhol", "Letras - Português E Francês", "Letras - Português E Grego",
      "Letras - Português E Hebraico", "Letras - Português E Inglês", "Letras - Português E Italiano",
      "Letras - Português E Japonês", "Letras - Português E Latim",
      "Letras - Português E Literaturas De Língua Portuguesa", "Letras - Português E Russo",
      "Letras - Português E Árabe", "Música - Bandolim", "Música - Cavaquinho", "Música - Clarineta",
      "Música - Contrabaixo", "Música - Cravo", "Música - Fagote", "Música - Flauta", "Música - Harpa",
      "Música - Instrumento De Percussão", "Música - Oboé", "Música - Regência Coral", "Música - Regência De Banda",
      "Música - Regência Orquestral", "Música - Saxofone", "Música - Trombone", "Música - Trompa",
      "Música - Trompete", "Música - Tuba", "Música - Viola", "Música - Violino", "Música - Violoncelo",
      "Música - Órgão", "Pintura", "Teoria Da Dança", "Atuação Cênica", "Cenografia E Indumentária",
      "Direção", "Estética E Teoria Do Teatro", "Letras - Japonês", "Comunicação Social - Cinema",
      "Letras - Português", "Tradutor Em Inglês", "Música - Instrumentos", "Música - Musicoterapia",
      "Música E Tecnologia", "Design De Animação", "Letras - Tradução Português E Inglês", "Letras - Tradutor",
      "Estudos Literários", "Linguística", "Design Digital", "Tradutor E Intérprete",
      "Letras - Inglês - Tradução E Interpretação", "Música - Percussão", "Música - Viola Caipira",
      "Música Com Habilitação Em Canto E Arte Lírica", "Música Com Habilitação Em Instrumento",
      "Tradução E Interpretação", "Imagem E Som",
      "Tradução E Interpretação Em Língua Brasileira De Sinais - Libras/Língua Portuguesa",
      "Artes Cênicas Com Habilitação Em Cenografia", "Artes Cênicas Com Habilitação Em Direção Teatral",
      "Artes Cênicas Com Habilitação Em Interpretação Teatral", "Artes Cênicas Com Habilitação Em Teoria Do Teatro",
      "Artes Visuais Com Habilitação Em Escultura", "Artes Visuais Com Habilitação Em Gravura",
      "Artes Visuais Com Habilitação Em Multimídia E Intermídia", "Artes Visuais Com Habilitação Em Pintura",
      "Letras - Armênio", "Letras - Chinês", "Letras - Coreano", "Letras - Espanhol", "Letras - Hebraico",
      "Letras - Latim", "Letras - Russo", "Letras - Árabe", "Música Com Habilitação Em Composição",
      "Música Com Habilitação Em Instrumento De Cordas - Ênfase Em Viola",
      "Música Com Habilitação Em Instrumento De Cordas - Ênfase Em Violino",
      "Música Com Habilitação Em Instrumento De Cordas - Ênfase Em Violoncelo",
      "Música Com Habilitação Em Instrumento De Cordas Dedilhadas - Ênfase Em Violão",
      "Música Com Habilitação Em Instrumento De Sopro - Ênfase Em Clarinete",
      "Música Com Habilitação Em Instrumento De Sopro - Ênfase Em Fagote",
      "Música Com Habilitação Em Instrumento De Sopro - Ênfase Em Flauta",
      "Música Com Habilitação Em Instrumento De Sopro - Ênfase Em Oboé",
      "Música Com Habilitação Em Instrumento De Sopro - Ênfase Em Trombone",
      "Música Com Habilitação Em Instrumento De Sopro - Ênfase Em Trompa",
      "Música Com Habilitação Em Instrumento De Sopro - Ênfase Em Trompete",
      "Música Com Habilitação Em Instrumento De Sopro - Ênfase Em Tuba",
      "Música Com Habilitação Em Instrumento De Teclado - Ênfase Em Piano",
      "Música Com Habilitação Em Instrumento De Teclado - Ênfase Em Órgão",
      "Música Com Habilitação Em Instrumento Percussão", "Música Com Habilitação Em Regência",
      "Superior Do Audiovisual", "Música - Composição E Regência", "Música - Teclado",
      "Letras Português E Inglês", "Arte: História, Crítica E Curadoria", "Comunicação Das Artes Do Corpo",
      "Comunicação E Multimeios", "Letras - Tradução Inglês E Português", "Artes Visuais, Pintura, Gravura E Escultura",
      "Tradução E Interpretação - Português/Inglês", "Cinema E Animação", "Design De Moda - Estilismo",
      "Design De Moda - Modelagem", "Fotografia", "Canto", "Design De Produto E Serviço", "Expressão Gráfica",
      "História - Memória E Imagem", "Letras - Polonês", "Letras - Português E Espanhol Ou Alemão Ou Grego Ou Latim",
      "Escultura", "Gravura", "Interdisciplinar Em Ciências E Humanidades", "Música - Produção Musical",
      "História - América Latina", "Mediação Cultural - Artes E Letras", "Engenharia De Design Digital",
      "Produção E Política Cultural", "Cinema De Animação", "Design De Jogos",
      "Letras - Redação E Revisão De Textos", "Letras - Tradução Espanhol - Português",
      "Letras - Tradução Inglês - Português", "Música - Ciências Musicais", "Comunicação Digital",
      "Interdisciplinar Em Humanidades, Artes E Tecnologia", "Realização Audiovisual",
      "Produção Em Mídia Audiovisual", "Comunicação Social - Habilitação Realização Audiovisual",
      "Animação", "Cinema", "Música - Violino E Viola"
    ]
  },
  {
    "area": "Artes e humanidades",
    "grau": 3.0,
    "cursos": [
      "Atuação Cênica", "Dança", "Produção Cultural", "Design De Interiores", "Design Gráfico",
      "Design De Animação", "Design De Moda", "Fotografia", "Design De Produto", "Produção Cênica",
      "Teatro", "Artes Do Espetáculo", "Política E Gestão Cultural", "Produção Musical",
      "Produção Multimídia", "Moda", "Produção Fonográfica", "Desenvolvimento Cênico",
      "Produção Audiovisual", "Design", "Mídias Digitais", "Filmmaker",
      "Produção Fonográfica - Produção Musical", "Cinema E Animação", "Conservação E Restauro",
      "Cinema E Audiovisual", "Cinema E Produção Audiovisual", "Artes E Mídias Digitais",
      "Comunicação Digital", "Design Digital", "Mídias Sociais Digitais", "Design Comercial",
      "Luteria", "Design Gráfico Digital", "Escrita Criativa"
    ]
  },
  {
    "area": "Ciências naturais, matemática e estatística",
    "grau": 1.0,
    "cursos": [
      "Biotecnologia", "Ciências Ambientais", "Ciências Biológicas", "Estatística", "Física",
      "Geofisica", "Geologia", "Matemática", "Química", "Química Tecnológica", "Química Industrial",
      "Matemática Industrial", "Ecologia E Análise Ambiental", "Física Médica",
      "Matemática Aplicada E Computacional", "Meteorologia", "Química Tecnológica E Industrial",
      "Interdisciplinar Em Ciência E Tecnologia", "Interdisciplinar Em Ciência, Tecnologia E Inovação",
      "Biologia", "Ciências Exatas E Tecnológicas - Bi/Li", "Interdisciplinar Em Ciências Ambientais",
      "Interdisciplinar Em Energia E Sustentabilidade", "Interdisciplinar Em Ciências", "Oceanologia",
      "Oceanografia", "Ecologia", "Ciências Atuariais", "Matemática Computacional",
      "Ciências Biológicas - Ênfase Em Ciências Ambientais", "Física De Materiais", "Química Do Petróleo",
      "Ciência E Tecnologia", "Astronomia", "Matemática Pura E Aplicada", "Ciências Atmosféricas",
      "Geofísica", "Interdisciplinar Em Ciências Da Terra - Bi/Li",
      "Interdisciplinar Em Ciências E Tecnologia Das Águas - Bi/Li", "Química Ambiental", "Gemologia",
      "Engenharia Geológica", "Bioquímica", "Ciências Exatas - Bi/Li",
      "Interdisciplinar Em Inovação, Ciência E Tecnologia", "Interdisciplinar Em Biossistemas",
      "Ciências Biológicas: Biofísica", "Ciências Biológicas: Biotecnologia", "Nanotecnologia",
      "Ciência Ambiental", "Ciências Biológicas - Biologia Marinha", "Ciências Biológicas - Biologia Vegetal",
      "Ciências Biológicas - Ecologia", "Ciências Biológicas - Genética", "Ciências Biológicas - Zoologia",
      "Ciências Biológicas: Microbiologia E Imunologia", "Ciências Matemáticas E Da Terra",
      "Ciências Matemáticas E Da Terra - Analista De Suporte À Decisão",
      "Ciências Matemáticas E Da Terra - Ciências Da Terra E Patrimônio Natural",
      "Ciências Matemáticas E Da Terra - Sensoriamento Remoto E Geoprocessamento", "Engenharia Matemática",
      "Matemática Aplicada", "Química - Atribuiçôes Tecnológicas",
      "Ciências Biológicas - Biotecnologia E Produção", "Ciências Biológicas - Gestão Ambiental",
      "Física Computacional", "Ciências Biológicas - Ênfase Em Biologia Ambiental",
      "Ciências Biológicas - Ênfase Em Biologia Evolutiva",
      "Ciências Biológicas - Ênfase Em Biologia Molecular E Tecnológica", "Matemática Aplicada A Negócios",
      "Química Com Habilitação Em Química Ambiental", "Química Com Habilitação Em Química Forense",
      "Química Com Habilitação Em Química Tecnológica", "Biotecnologia E Agroindustria",
      "Interdisciplinar Em Ciência E Tecnologia Do Mar - Bi/Li", "Neurociência",
      "Ciências Físicas E Biomoleculares", "Ciências Físicas E Biomoleculares - Ênfase Tecnológica",
      "Estatística E Ciência De Dados", "Física Com Habilitação Em Óptica E Fotônica",
      "Física Com Habilitação Teórico - Experimental", "Matemática Aplicada E Computação Científica",
      "Química - Habilitação Fundamental", "Química - Habilitação Tecnológica - Ênfase Ambiental",
      "Química - Habilitação Tecnológica - Ênfase Em Alimentos",
      "Química - Habilitação Tecnológica - Ênfase Em Materiais",
      "Química - Habilitação Tecnológica - Ênfase Gestão De Qualidade", "Física Biológica",
      "Ciências Moleculares", "Matemática Aplicada Com Habilitação Em Ciências Biológicas",
      "Matemática Aplicada Com Habilitação Em Controle E Automação",
      "Matemática Aplicada Com Habilitação Em Métodos Matemáticos",
      "Matemática Aplicada Com Habilitação Em Sistemas E Controle",
      "Matemática Aplicada E Computacional Com Habilitação Em Atuária",
      "Matemática Aplicada E Computacional Com Habilitação Em Ciências Biológicas",
      "Matemática Aplicada E Computacional Com Habilitação Em Comunicação Científica",
      "Matemática Aplicada E Computacional Com Habilitação Em Estatística Econômica",
      "Matemática Aplicada E Computacional Com Habilitação Em Fisiologia E Biofísica",
      "Matemática Aplicada E Computacional Com Habilitação Em Mecatrônica E Sistemas Mecânicos",
      "Matemática Aplicada E Computacional Com Habilitação Em Métodos Matemáticos",
      "Matemática Aplicada E Computacional Com Habilitação Em Saúde Animal",
      "Matemática Aplicada E Computacional Com Habilitação Em Saúde Pública",
      "Matemática Aplicada E Computacional Com Habilitação Em Sistemas E Controle",
      "Química Com Ênfase Em Bioquímica E Biologia Molecular", "Química Com Ênfase Em Biotecnologia",
      "Química Com Ênfase Em Química Ambiental", "Química Com Ênfase Química Tecnológica",
      "Ciências Biológicas - Ecologia E Biodiversidade", "Matemática Empresarial",
      "Química - Química Forense", "Química Medicinal", "Ciências Biológicas - Biodiversidade E Conservação",
      "Biotecnologia Industrial"
    ]
  },
  {
    "area": "Ciências naturais, matemática e estatística",
    "grau": 3.0,
    "cursos": [
      "Processos Químicos", "Geoprocessamento", "Biotecnologia", "Cosméticos",
      "Paisagismo E Jardinagem", "Toxicologia Analítica", "Toxicologia Ambiental"
    ]
  },
  {
    "area": "Ciências sociais, comunicação e informação",
    "grau": 1.0,
    "cursos": [
      "Arquivologia", "Biblioteconomia", "Ciência Política", "Ciências Econômicas", "Ciências Sociais",
      "Ciências Sociais - Antropologia", "Ciências Sociais - Sociologia", "Comunicação Social - Audiovisual",
      "Geografia", "Jornalismo", "Museologia", "Psicologia", "Psicologia - Psicólogo",
      "Relações Internacionais", "Jornalismo Digital", "Comunicação Social - Jornalismo",
      "Ciências Sociais - Políticas Públicas", "Gestão Da Informação", "Comunicação Social  - Radialismo",
      "Comunicação Social - Cinema", "Comunicação Social - Rádio E Televisão",
      "Comunicação Social - Rádio, Tv E Internet", "Mídia E Tecnologia", "Jornalismo Em Multimeios",
      "Comunicação Social", "Antropologia", "Biblioteconomia E Documentação",
      "Comunicação - Produção Em Comunicação E Cultura", "Estudo De Gênero E Diversidade",
      "Interdisciplinar Em Humanidades", "Publicidade E Propaganda", "Comunicação Social - Produção Editorial",
      "Mídias Digitais", "Ciência Econômica", "Comunicação Social - Publicidade E Propaganda",
      "Economia Ecológica", "Radialismo", "Estudos De Mídia", "Ciências Do Consumo",
      "Comunicação Social - Radialismo, Rádio, Tv E Internet", "Economia", "Gestão Territorial Indígena",
      "Ciências Socioambientais", "Relações Econômicas Internacionais", "Políticas Públicas E Gestão Social",
      "Interdisciplinar Em Ciência E Economia - Bi/Li", "Políticas Públicas", "Sociologia",
      "Biblioteconomia E Gestão De Unidades De Informação", "Defesa E Gestão Estratégica Internacional",
      "Neurociências", "Comunicação Digital", "Comunicação: Rádio, Televisão E Internet",
      "Biblioteconomia E Ciência Da Informação", "Economia Empresarial E Controladoria Com Habilitação Em Economia",
      "Psicologia - Formação De Psicólogo", "Interdisciplinar Em Ciências E Humanidades", "Planejamento Territorial",
      "Comunicação Social Com Habilitação Em Editoração", "Cinema E Audiovisual",
      "Comunicação Social - Radialismo (Rádio E Tv)", "Relações Públicas", "Sociologia E Política",
      "Interdisciplinar Em Ciências Do Trabalho", "Criminologia", "Antropologia - Diversidade Cultural Latino-Americana",
      "Ciência Política E Sociologia - Sociedade, Estado E Política Na América Latina",
      "Ciências Econômicas - Economia, Integração E Desenvolvimento",
      "Desenvolvimento Rural E Segurança Alimentar", "Relações Internacionais E Integração",
      "Comunicação E Multimeios", "Ontopsicologia",
      "Comunicação Social -Radialismo - Produção Em Mídia Audiovisual", "Ciências Sociais - Ciência Política",
      "Ciência Da Informação"
    ]
  },
  {
    "area": "Ciências sociais, comunicação e informação",
    "grau": 3.0,
    "cursos": ["Social Media", "Recrutamento, Seleção E Desenvolvimento De Pessoas"]
  },
  {
    "area": "Computação e Tecnologias da Informação e Comunicação (TIC)",
    "grau": 1.0,
    "cursos": [
      "Ciência Da Computação", "Engenharia De Software", "Sistemas De Informação",
      "Ciência De Dados E Inteligência Artificial", "Sistema De Informação",
      "Ciência De Dados E Machine Learning", "Inteligência Artificial", "Informática",
      "Ciências Da Computação", "Ciência De Dados", "Sistemas E Mídias Digitais", "Design Digital",
      "Ciência De Dados Para Negócios", "Computação", "Tecnologia Da Informação",
      "Interdisciplinar Em Tecnologia Da Informação - Bi/Li", "Jogos Digitais", "Cibersegurança",
      "Informática Biomédica", "Inteligência Artificial E Ciência De Dados", "Ciências De Computação",
      "Design De Games", "Arquitetura E Desenvolvimento De Software", "Criação Digital",
      "Tecnologias Digitais", "Tecnologias Da Informação E Comunicação"
    ]
  },
  {
    "area": "Computação e Tecnologias da Informação e Comunicação (TIC)",
    "grau": 3.0,
    "cursos": [
      "Gestão Da Tecnologia Da Informação", "Análise E Desenvolvimento De Sistemas", "Jogos Digitais",
      "Redes De Computadores", "Banco De Dados", "Ciências De Dados", "Segurança Da Informação",
      "Sistemas Para Internet", "Ciência De Dados E Inteligência Artificial", "Inteligência Artificial",
      "Agrocomputação", "Defesa Cibernética", "Ciência De Dados", "Sistemas De Computação", "Devops",
      "Processamento De Dados", "Bioinformática", "Inteligência Artificial E Ciência De Dados",
      "Sistema De Informação", "Tecnologias Da Informação E Comunicação",
      "Análise E Desenvolvimento De Sistemas Do Programa Ams", "Desenvolvimento De Software Multiplataforma",
      "Desenvolvimento De Sistemas", "Design De Mídias Digitais",
      "Tecnologia Em Desenvolvimento De Software Multiplataforma", "Análise De Processos Agroindustriais",
      "Informática Para Negócios", "Big Data No Agronegócio", "Desenvolvilmento De Software Multiplataformas",
      "Segurança Cibernética", "Informática", "Informática Em Saúde", "Computação Em Nuvem", "Data Science",
      "Game Development", "Web Design", "Big Data E Inteligência Analítica", "Big Data Para Negócios",
      "Ciência De Dados Para Negócios", "Tecnologias Educacionais",
      "Inteligência Artificial E Machine Learning", "Ciência De Dados E Inteligência Analítica"
    ]
  },
  {
    "area": "Educação",
    "grau": 1.0,
    "cursos": ["Pedagogia", "Psicopedagogia"]
  },
  {
    "area": "Educação",
    "grau": 2.0,
    "cursos": [
      "Artes Cênicas", "Artes Visuais", "Ciências Biológicas", "Ciências Naturais", "Ciências Sociais",
      "Computação", "Educação Do Campo", "Educação Física", "Filosofia", "Física", "Geografia",
      "História", "Letras - Francês",
      "Letras - Língua De Sinais Brasileira/Português Como Segunda Língua",
      "Letras - Língua E Literatura Japonesa",
      "Letras - Língua Espanhola E Literatura Espanhola E Hispano-Americana",
      "Letras - Língua Inglesa E Respectiva Literatura",
      "Letras - Língua Portuguesa E Respectiva Literatura",
      "Letras - Português Do Brasil Como Segunda Língua", "Matemática", "Música", "Pedagogia",
      "Psicologia", "Química", "Letras - Inglês", "Letras - Português", "Letras - Português E Inglês",
      "Letras", "Biologia", "Dança", "Educação Profissional E Tecnológica", "Letras - Espanhol",
      "Letras - Língua Portuguesa", "Letras - Língua Portuguesa, Língua Inglesa E Suas Respectivas Literaturas",
      "Pedagogia Bilíngue", "Educação Intercultural - Ciências Da Cultura",
      "Educação Intercultural - Ciências Da Linguagem", "Educação Intercultural - Ciências Da Natureza",
      "Letras: Espanhol", "Letras: Francês", "Letras: Inglês", "Letras: Libras", "Letras: Português",
      "Música - Canto", "Música - Educação Musical", "Música - Instrumento Musical", "Teatro",
      "Educação Bilíngue: Português E Libras",
      "Interdisciplinar Em Educação Do Campo: Ciências Humanas E Sociais",
      "Interdisciplinar Em Educação Escolar Quilombola: Ciências Humanas", "Letras - Português-Inglês",
      "Pedagogia Inclusiva E Educação Especial", "Licenciatura Intercultural Indígena",
      "Letras - Língua Portuguesa E Literaturas De Língua Portuguesa", "Ciências Da Natureza - Química",
      "Educação Escolar Quilombola", "Letras - Libras", "Letras - Português E Literaturas",
      "Letras Português E Espanhol E Respectivas Literaturas", "Letras Português E Francês",
      "Letras Português E Inglês", "Letras - Português E Inglês E Respectivas Literaturas",
      "Educação Bilíngue De Surdos", "Letras - Português E Espanhol", "Ciências Da Natureza - Biologia",
      "Ciências Da Natureza", "Educação Especial E Inclusiva",
      "Letras - Língua E Literaturas De Língua Inglesa", "Ciências Naturais E Matemática - Física",
      "Ciências Naturais E Matemática - Matemática", "Ciências Naturais E Matemática - Química",
      "Pedagogia Intercultural", "Pedagogia Intercultural Indígena",
      "Interdisciplinar Em Ciências Naturais", "Educação Do Campo - Ciências Da Natureza E Ciências Humanas",
      "Interdisciplinar Em Educação No Campo", "Letras - Português E Francês",
      "Língua E Literaturas Da Língua Inglesa", "Língua Portuguesa E Respectivas Literaturas",
      "Ciências: Biologia, Física E Química", "Intercultural Indígena Em Ciências Sociais",
      "Intercultural Indígena Em Línguas, Artes E Literatura",
      "Intercultural Indígena Em Matemática E Ciências Naturais", "Intercultural Indígena Em Pedagogia",
      "Letras - Língua Inglesa E Respectivas Literaturas", "Educação Do Campo - Ciências Agrárias",
      "Letras - Libras/Língua Estrangeira", "Educação Quilombola",
      "Educação Do Campo - Ciências Da Natureza Ou Matemática.",
      "Pedagogia - Educação Infantil E Anos Iniciais Do Ensino Fundamental",
      "Interdisciplinar Em Artes E Suas Tecnologias",
      "Interdisciplinar Em Ciências Da Natureza E Suas Tecnologias",
      "Interdisciplinar Em Ciências Humanas E Sociais E Suas Tecnologias",
      "Interdisciplinar Em Linguagens E Suas Tecnologias",
      "Interdisciplinar Em Matemática E Computação E Suas Tecnologias",
      "Pedagogia - Programa De Formação Inicial De Professores - Para Atuação Na Educação Infantil E Anos Iniciais Do Ensino Fundamental",
      "Letras - Português E Literaturas Da Língua Portuguesa", "Letras - Língua Portuguesa E Língua Inglesa",
      "Intercultural Indígena", "Desenho E Plástica", "Letras - Língua Estrangeira", "Letras Vernáculas",
      "Letras Vernáculas - Língua Estrangeira", "Letras Vernáculas -Português - Língua Estrangeira",
      "Interdisciplinar Em Artes", "Música - Música Popular Brasileira", "Ciências Agrárias",
      "Ciências Da Computação", "Eletromecânica", "Letras Modernas - Português/Inglês E Respectivas Literaturas",
      "Letras Vernáculas - Português E Respectivas Literaturas", "Interdisciplinar Em Educação Do Campo",
      "Letras - Português E Alemão", "Letras - Português E Italiano", "Educação Especial Inclusiva",
      "Letras - Língua Inglesa", "Sociologia", "Ciências Humanas - Sociologia", "Ciências Naturais - Biologia",
      "Ciências Naturais - Física", "Educação Do Campo - Ciências Da Natureza E Matemática",
      "Programa Especial De Formação Pedagógica De Docentes", "Ciências Humanas - História",
      "Ciências Humanas - Geografia", "Ciências Naturais - Química", "Ciências Humanas - Filosofia",
      "Linguagens E Códigos - Língua Portuguesa", "Linguagens E Códigos - Música",
      "Interdisciplinar Em Estudos Africanos E Afro-Brasileiros",
      "Letras - Língua Portuguesa E Língua Francesa", "Ciências Das Religiões",
      "Letras - Letras Clássicas (Grego E Latim)", "Pedagogia - Educação Do Campo", "Ciência Da Computação",
      "Letras Com Português E Espanhol", "Pedagogia - Docencia Da Educação Infantil/Administração Educacional",
      "Expressão Gráfica", "Educação Do Campo - Ciências Humanas E Sociais",
      "Educação Do Campo - Ciências Da Natureza", "Pedagogia Da Terra", "Computação E Informática",
      "Pedagogia Bilíngue: Libras/Língua Portuguesa", "Letras - Lingua Espanhola", "Informática",
      "Educação Intercultural Indígena", "Letras - Língua Portuguesa E Libras", "Ciências Da Religião",
      "Formação De Docentes Para A Educação Básica", "Indígena", "Artes Cênicas - Teatro",
      "Letras - Libras - Português", "Educação Do Campo - Ciências Agrárias E Biologia",
      "Ciências - Química E Biologia", "Ciências Agrárias E Do Ambiente",
      "Letras - Língua E Literatura Portuguesa E Língua E Literatura Espanhola", "Pedagogia Do Campo",
      "Ciências - Matemática E Física",
      "Letras - Língua E Literatura Portuguesa E Língua E Literatura Inglesa",
      "Formação De Professores Indígenas", "Letras - Língua E Literatura Espanhola",
      "Letras - Língua E Literatura Francesa", "Letras - Língua E Literatura Inglesa",
      "Letras - Língua E Literatura Portuguesa",
      "Licenciatura Indígena Políticas Educacionais E Desenvolvimento Sustentável", "Ciência Da Religião",
      "Etnodesenvolvimento", "Letras - Alemão", "Licenciatura Integrada Em Ciências, Matemática E Linguagens",
      "Informática Educacional", "Licenciatura Integrada Em Biologia E Química",
      "Licenciatura Integrada Em História E Geografia", "Licenciatura Integrada Em Matemática E Física",
      "Ciências - Química/Biologia", "Educação Básica Intercultural",
      "Educação Especial Inclusiva Intercultural", "Licenciatura Intercultural - Ciências Da Natureza",
      "Licenciatura Intercultural - Ciências Sociais", "Licenciatura Intercultural - Comunicação E Artes",
      "Ciências Da Natureza - Biologia, Física E Química", "Letras - Espanhol E Literatura Hispânica",
      "Ciências Humanas", "Educação Do Campo - Linguagens E Códigos (Artes E Música)",
      "Educação Do Campo - Linguagens E Códigos: Artes (Artes Visuais, Artes Cênicas E Música)",
      "Ciências Agrícolas", "Programa Especial De Formação Docente Em Artes",
      "Programa Especial De Formação Docente Em Matemática",
      "Programa Especial De Formação Pedagógica Para Docentes Para As Disciplinas Do Currículo Do Ensino Fundamental, Médio E Da Educação Profissional Em Nível Médio",
      "Educação Indígena", "Letras  - Inglês E Literaturas Da Língua Inglesa",
      "Letras - Espanhol E Literaturas De Língua Espanhola",
      "Formação Intercultural Para Educadores Indígenas", "Artes Plásticas",
      "Música - Educação Musical Escolar", "Programa Especial De Formação De Docente", "Enfermagem",
      "Letras Português E Suas Literaturas", "Letras Português, Inglês E Suas Literaturas",
      "Letras - Língua Inglesa E Suas Literaturas", "Letras - Francês E Literaturas De Língua Francesa",
      "Letras - Língua Portuguesa Com Domínio De Libras",
      "Letras - Português E Literaturas De Língua Portuguesa", "Educação Infantil",
      "Ciências Da Natureza: Ciências E Biologia", "Ciências Da Natureza: Ciências E Física",
      "Ciências Da Natureza: Ciências E Química", "Cinema E Audiovisual", "Letras - Grego",
      "Letras - Italiano", "Letras - Latim", "Letras - Português E Grego", "Letras - Português E Hebraico",
      "Letras - Português E Japonês", "Letras - Português E Latim", "Letras - Português E Russo",
      "Letras - Português E Árabe", "Biblioteconomia", "Letras - Japonês", "Letras - Português E Literatura",
      "Normal  Superior", "Belas Artes", "Ciências Biológicas - Licenciatura Ou Bacharelado", "Artes",
      "Ciências", "Educação Artística", "Programa Especial De Formação De Docentes Para A Educação Básica",
      "Educação Artística Com Habilitação Em Música", "Interdisciplinar Em Ciências Naturais E Exatas",
      "Interdisciplinar Em Ciências Humanas - Bi/Li", "Educação Especial",
      "Ciências Exatas Com Habilitação Em Física", "Ciências Exatas Com Habilitação Em Matemática",
      "Ciências Exatas Com Habilitação Em Química", "Ciências Naturais: Habilitação Em Física",
      "Ciências Naturais: Habilitação Em Química", "Educomunicação", "Geociências E Educação Ambiental",
      "Educação Artística - Música", "Linguagem",
      "Letras - Língua Portuguesa E Língua Inglesa E Respectivas Literaturas",
      "Letras - Língua Portuguesa E Língua Espanhola E Respectivas Literaturas",
      "Letras - Língua Portuguesa E Língua Italiana E Respectivas Literaturas",
      "Letras - Português E Polonês", "Letras - Espanhol E Português Como Línguas Estrangeiras", "Arte",
      "Pedagogia: Docência Na Educação Infantil E Anos Iniciais Do Ensino Fundamental No Contexto Do Campo",
      "Teologia", "Ciências Exatas - Física", "Ciências Exatas - Matemática", "Ciências Exatas - Química",
      "Educação Do Campo: Ciências Sociais E Humanas",
      "Interdisciplinar Em Educação Do Campo: Ciências Da Natureza",
      "Interdisciplinar Em Educação Do Campo: Ciências Naturais, Matemática E Ciências Agrárias",
      "Letras - Língua Portuguesa E Respectivas Literaturas E Língua Alemã",
      "Letras - Língua Portuguesa E Respectivas Literaturas E Língua Espanhola",
      "Letras - Língua Portuguesa E Respectivas Literaturas E Língua Inglesa",
      "Música Com Habilitação Em Licenciatura Em Educação Musical", "Linguagem E Comunicação",
      "Letras - Línguas Adicionais Inglês, Espanhol E Respectivas Literaturas", "Ciências Exatas",
      "Programa Especial Formação De Professores Para Os Componentes Curriculares Da Educação Profissional",
      "Letras Libras/Literatura Surda", "Formação Pedagógica Para Graduados Não Licenciados",
      "Letras - Língua Portuguesa E Respectivas Literaturas", "Ciências Da Natureza - Biologia E Química",
      "Programa Especial De Formação Pedagógica De Docentes Para A Educação Profissional",
      "Programa Especial De Graduação De Formação De Professores Para A Educação Profissional",
      "Formação Pedagógica De Docentes Para A Educação Básica E Profissional.",
      "Intercultural Indígena Com Ênfase Em Linguagens", "Tecnologia Educacional",
      "Pedagogia - Anos Iniciais Do Ensino Fundamental",
      "Intercultural Em Letras-Língua Portuguesa, Língua Kaingang E Respectivas Literaturas",
      "Ciências Da Religião - Ensino Religioso", "Tecnologias Educacionais",
      "Pedagogia Bilingue  - Libras/Português"
    ]
  },
  {
    "area": "Educação",
    "grau": 3.0,
    "cursos": ["Processos Escolares", "Psicomotricidade E Ludicidade Na Educação Infantil"]
  },
  {
    "area": "Engenharia, produção e construção",
    "grau": 1.0,
    "cursos": [
      "Arquitetura E Urbanismo", "Engenharia Aeroespacial", "Engenharia Ambiental",
      "Engenharia Automotiva", "Engenharia Civil", "Engenharia De Computação", "Engenharia De Energia",
      "Engenharia De Produção", "Engenharia De Redes De Comunicação", "Engenharia Eletrônica",
      "Engenharia Elétrica", "Engenharia Mecatrônica - Controle E Automação", "Engenharia Mecânica",
      "Engenharia Química", "Gestão Ambiental", "Engenharia De Controle E Automação",
      "Engenharia Ambiental E Sanitária", "Engenharia Mecatrônica", "Engenharia Civil Da Mobilidade",
      "Engenharia De Materiais", "Engenharia De Transportes", "Engenharia De Minas",
      "Engenharia De Alimentos", "Engenharia Física", "Engenharia Da Computação",
      "Engenharia Cartográfica E De Agrimensura", "Ciência E Tecnologia De Alimentos",
      "Engenharia De Produção Agroindustrial", "Engenharia Sanitaria E Ambiental", "Engenharia De Petróleo",
      "Engenharia Sanitária E Ambiental", "Engenharia De Energias",
      "Engenharia De Tecnologia Assistiva E Acessibilidade", "Engenharia Agroindustrial",
      "Engenharia Ambiental E Da Sustentabilidade", "Engenharia De Transportes E Logística",
      "Engenharia De Bioprocessos E Biotecnologia", "Engenharia De Produção Mecânica",
      "Engenharia De Telecomunicações", "Engenharia De Biotecnologia",
      "Engenharia De Agrimensura E Cartográfica", "Engenharia De Controle E Automação De Processos",
      "Engenharia De Produção Civil", "Engenharia De Petróleo E Gás", "Engenharia Industrial Elétrica",
      "Engenharia Agrícola E Ambiental", "Engenharia De Energias Renováveis",
      "Engenharia De Teleinformática", "Engenharia Metalúrgica", "Engenharia De Mecatrônica", "Engenharia",
      "Engenharia Industrial Mecânica", "Engenharia De Biotecnologia E Bioprocessos", "Engenharia Hídrica",
      "Engenharia Biomédica", "Engenharia Naval", "Engenharia Elétrica - Eletrotécnica",
      "Engenharia Elétrica - Eletrônica", "Engenharia Elétrica - Telecomunicações",
      "Engenharia Da Complexidade", "Engenharia Têxtil", "Engenharia Ambiental E Energias Renováveis",
      "Engenharia De Bioprocessos", "Engenharia Ferroviária E Logística",
      "Engenharia De Minas E Meio Ambiente", "Engenharia Costeira E Oceânica",
      "Engenharia De Exploração E Produção De Petróleo", "Engenharia Industrial Madeireira",
      "Engenharia De Automação Industrial", "Engenharia De Sistemas", "Engenharia Aeronáutica",
      "Engenharia Eletrônica E De Telecomunicações", "Engenharia De Agrimensura",
      "Engenharia Civil E Ambiental", "Engenharia De Produção E Qualidade", "Engenharia Da Mobilidade",
      "Engenharia De Saúde E Segurança", "Engenharia Mecânica Aeronáutica", "Engenharia Computacional",
      "Engenharia Elétrica - Energia", "Engenharia Elétrica - Robótica E Automação Industrial",
      "Engenharia Elétrica - Sistemas De Potência", "Engenharia Elétrica - Sistemas Eletrônicos",
      "Engenharia Urbana", "Ciência E Tecnologia De Laticínios", "Engenharia Ferroviária E Metroviária",
      "Interdisciplinar Em Inovação, Ciência E Tecnologia", "Saúde Coletiva",
      "Engenharia De Recursos Hídricos E Do Meio Ambiente", "Engenharia De Computação E Informação",
      "Engenharia Eletrônica E De Computação", "Engenharia Naval E Oceânica", "Engenharia Nuclear",
      "Paisagismo", "Engenharia Cartográfica", "Engenharia De Materiais E Nanotecnologia",
      "Engenharia De Comunicações", "Engenharia De Fortificação E Construção",
      "Engenharia Mecânica E De Armamento", "Engenharia Mecânica E De Automóvel",
      "Engenharia De Agronegócios", "Engenharia De Automação E Controle", "Engenharia Industrial - Madeira",
      "Engenharia De Manufatura", "Engenharia Bioquímica", "Engenharia Industrial Química",
      "Ciências Dos Alimentos", "Engenharia Ambiental E Urbana", "Engenharia De Informação",
      "Engenharia De Instrumentação, Automação E Robótica", "Engenharia De Gestão", "Engenharia De Robôs",
      "Gestão E Análise Ambiental", "Engenharia De Materiais E Manufatura",
      "Engenharia Elétrica - Ênfase Em Eletrônica", "Engenharia Elétrica - Ênfase Em Sistemas De Energia E Automação",
      "Engenharia Mecânica - Ênfase Em Mecânica Plena", "Engenharia Aeronáutica E Espaço",
      "Engenharia De Computação - Ênfase Sistemas Corporativos", "Engenharia Elétrica  - Ênfase Em Computação",
      "Engenharia Elétrica - Ênfase Em Automação E Controle",
      "Engenharia Elétrica - Ênfase Em Eletrônica E Sistemas Computacionais",
      "Engenharia Elétrica - Ênfase Em Energia E Automação Elétricas",
      "Engenharia Elétrica - Ênfase Em Telecomunicações", "Têxtil E Moda",
      "Engenharia De Sistemas Ciber Físicos", "Engenharia Elétrica E Eletrônica",
      "Engenharia Civil De Infraestrutura", "Engenharia Mecânica Automotiva", "Química De Alimentos",
      "Engenharia Civil Costeira E Portuária", "Engenharia Civil Empresarial", "Engenharia De Automação",
      "Engenharia Mecânica Empresarial", "Engenharia Mecânica Naval", "Engenharia Acústica",
      "Engenharia Agroindustrial Agroquímica", "Engenharia Agroindustrial Indústrias Alimentícias",
      "Engenharia De Gestão De Energia", "Engenharia De Serviços", "Engenharia De Produção Elétrica",
      "Engenharia Sanitária", "Engenharia De Transporte E Logística", "Engenharia De Produção E Sistemas",
      "Engenharia De Producao - Habilitacao Mecanica"
    ]
  },
  {
    "area": "Engenharia, produção e construção",
    "grau": 3.0,
    "cursos": [
      "Gestão Ambiental", "Alimentos", "Automação Industrial", "Construção De Edifícios", "Agrimensura",
      "Mineração", "Saneamento Ambiental", "Sistemas Biomédicos", "Controle De Obras",
      "Mecânica De Precisão", "Eletrotécnica Industrial", "Processos Metalúrgicos",
      "Produção Sucroalcooleira", "Sistemas Elétricos", "Laticínios", "Manutenção Industrial",
      "Petróleo E Gás", "Mecatrônica Industrial", "Energias Renováveis", "Estradas", "Telemática",
      "Construção Civil", "Sistemas De Telecomunicações", "Tecnologia Eletrônica", "Eletrônica Industrial",
      "Rochas Ornamentais", "Manutenção De Aeronaves", "Produção De Cachaça", "Construção Naval", "Polímeros",
      "Redes De Telecomunicações", "Produção Têxtil", "Têxtil E Moda", "Biocombustíveis",
      "Celulose E Papel", "Gestão De Energia E Eficiência Energética", "Fabricação Mecânica",
      "Manufatura Avançada", "Meio Ambiente E Recursos Hídricos", "Sistemas Navais", "Sistemas Embarcados",
      "Controle Ambiental", "Tecnologia Em Controle Ambiental", "Desenvolvimento De Produtos Plásticos",
      "Projetos Mecânicos", "Mecânica: Processos De Soldagem", "Eletrônica Automotiva",
      "Mecânica Automobilística", "Automação E Manufatura Digital", "Projeto De Estruturas Aeronáuticas",
      "Produção De Vestuário", "Produção Gráfica", "Sistemas Automotivos",
      "Construção Civil - Modalidade Edifícios", "Hidráulica E Saneamento Ambiental", "Instalações Elétricas",
      "Materiais", "Mecânica - Modalidade Processos De Produção", "Mecânica - Modalidade Projetos",
      "Microeletrônica", "Soldagem", "Refrigeração, Ventilação E Ar Condicionado", "Processos Ambientais",
      "Meio Ambiente", "Cerâmica", "Sistemas De Energia"
    ]
  },
  {
    "area": "Negócios, administração e direito",
    "grau": 1.0,
    "cursos": [
      "Administração", "Ciências Contábeis", "Comunicação Social - Comunicação Organizacional",
      "Comunicação Social - Publicidade E Propaganda", "Direito", "Gestão De Agronegócios",
      "Gestão De Políticas Públicas", "Gestão Do Agronegócio", "Secretariado Executivo - Bilíngue",
      "Publicidade E Propaganda", "Administração Pública", "Secretariado Executivo", "Relações Públicas",
      "Propaganda E Marketing", "Comércio Exterior", "Comunicação Social", "Políticas Públicas",
      "Administração Hospitalar", "Gestão Pública E Social", "Administração Pública E Gestão Social",
      "Comunicação E Marketing", "Finanças", "Marketing", "Negócios", "Administração De Empresas",
      "Ciências Imobiliárias", "Comunicação Social - Relações Públicas", "Gestão Pública",
      "Secretariado Executivo Trilíngue", "Gestão Pública E Desenvolvimento Regional",
      "Ciência De Dados Para Negócios", "Ciências Do Estado", "Controladoria E Finanças", "Agronegócio",
      "Cooperativismo", "Gestão Pública Para O Desenvolvimento Econômico E Social",
      "Comunicação Social - Jornalismo", "Mídias Digitais", "Tecnologia Da Informação Para Negócios Digitais",
      "Gestão De Negócios E Inovação", "Comércio Exterior E Negócios Internacionais", "Marketing E Publicidade",
      "Economia Empresarial E Controladoria Com Habilitação Em Contabilidade", "Finanças E Negócios",
      "Comunicação Social Com Habilitação Em Publicidade E Propaganda", "Comércio Internacional",
      "Negócios Da Moda", "Engenharia De Custos", "Comunicação Organizacional", "Negócios Internacionais",
      "Comunicação E Inteligência De Mercado", "Criminologia", "Comunicação Digital", "Mercado Financeiro",
      "Negócios Digitais", "Administração Pública E Políticas Públicas", "Gestão E Empreendedorismo",
      "Gestão Integrada De Agronegócios", "Administração Pública E Social", "Ciências Jurídicas E Sociais",
      "Gestão Em Saúde", "Administração Em Sistemas E Serviços De Saúde", "Desenvolvimento Regional", "Logística"
    ]
  },
  {
    "area": "Negócios, administração e direito",
    "grau": 3.0,
    "cursos": [
      "Gestão Pública", "Gestão De Recursos Humanos", "Gestão De Cooperativas", "Gestão Financeira",
      "Gestão Comercial", "Gestão Hospitalar", "Marketing E Inteligência De Dados", "Marketing",
      "Gestão De Serviços Jurídicos E Notariais", "Processos Gerenciais", "Secretariado", "Logística",
      "Gestão Da Produção Industrial", "Gestão Do Agronegócio", "Agronegócio", "Gestão Executiva De Negócios",
      "Gestão De Negócios E Inovação", "Gestão De Saúde", "Comércio Exterior",
      "Tecnologia Em Gestão E Inovação Em Agronegócio", "Gestão Da Qualidade", "Produção Publicitária",
      "Gestão De Negócios Imobiliários", "Gestão De Marketing Em Mídias Digitais",
      "Gestão De Produção Industrial", "Organização De Serviços Judiciários", "Gestão Em Saúde",
      "Gestão Da Inovação E Empreendedorismo Digital", "Gestão De Processos E Projetos Ágeis",
      "Marketing Digital", "Investimento E Formação De Traders", "Gestão De Agronegócios",
      "Gestão Empreendedora", "Gestão De Seguros", "Gestão Da Avaliação", "Gestão Empresarial",
      "Comunicação Institucional", "Logística Aeroportuária", "Gestão De Serviços",
      "Gestão De Logística Integrada", "Produção Industrial", "Gestão De Negócios Digitais",
      "Gestão Fiscal E Tributária", "Gestão De Pessoas", "Secretariado E Assessoria Internacional",
      "Empreendedorismo", "Logística Do Programa Ams", "Processos Gerenciais Do Programa Ams",
      "Inteligência De Mercado E Análise De Dados", "Serviços Jurídicos", "Gestão Imobiliária",
      "Comunicação Empresarial"
    ]
  },
  {
    "area": "Saúde e bem-estar",
    "grau": 1.0,
    "cursos": [
      "Educação Física", "Enfermagem", "Farmácia", "Fisioterapia", "Fonoaudiologia", "Medicina",
      "Nutrição", "Odontologia", "Saúde Coletiva", "Serviço Social", "Terapia Ocupacional",
      "Biomedicina", "Bacharelado Interdisciplinar Em Ciências Médicas", "Musicoterapia",
      "Ciências Biológicas - Modalidade Médica", "Enfermagem Intercultural Indígena",
      "Interdisciplinar Em Saúde", "Optometria", "Educação Física - Promoção Em Saúde E Lazer",
      "Educação Física - Treinamento Esportivo", "Quiropraxia", "Gestão Em Saúde Coletiva Indígena",
      "Enfermagem E Obstetrícia", "Gestão De Serviços De Saúde", "Naturologia",
      "Interdisciplinar Em Saúde E Bem-Estar", "Ciências Biológicas: Modalidade Médica",
      "Ciências Biomédicas", "Ciência Do Esporte", "Óptica E Optometria",
      "Ciências Biomédicas - Ênfase Em Biotecnologia Em Saúde",
      "Ciências Biomédicas - Ênfase Em Ciências Básicas Da Saúde",
      "Educação Física E Esporte - Ênfase Em Educação Física E Saúde",
      "Educação Física E Esporte - Ênfase Em Esporte", "Farmácia E Bioquímica", "Nutrição E Metabolismo",
      "Gerontologia", "Ciências Fundamentais Para A Saúde",
      "Educação Física Com Ênfase Em Treinamento E Gestão No Esporte", "Educação Física E Saúde",
      "Esporte", "Obstetrícia", "Saúde Pública", "Podologia"
    ]
  },
  {
    "area": "Saúde e bem-estar",
    "grau": 3.0,
    "cursos": ["Radiologia", "Óptica E Optometria", "Optometria", "Oftálmica", "Podologia", "Acupuntura", "Massoterapia"]
  },
  {
    "area": "Serviços",
    "grau": 1.0,
    "cursos": [
      "Turismo", "Ciências Policiais", "Formação De Oficiais Bombeiro Militar - Cfo/Bm",
      "Turismo E Patrimônio", "Ciências Aeronáuticas", "Estética E Cosmética", "Turismo E Hotelaria",
      "Gastronomia", "Hotelaria", "Formação De Oficiais (Ccsa)", "Formação De Oficiais Bombeiro Militar",
      "Estética", "Segurança Pública", "Ciências Militares", "Lazer E Turismo", "Aviação Civil",
      "Turismo E Negócios", "Ciências Policiais E Segurança Pública", "Gestão E Resposta A Emergências"
    ]
  },
  {
    "area": "Serviços",
    "grau": 3.0,
    "cursos": [
      "Estética E Cosmética", "Gastronomia", "Pilotagem Profissional De Aeronaves", "Segurança No Trabalho",
      "Segurança Pública", "Eventos", "Hotelaria", "Gestão De Turismo", "Turismo", "Transporte Terrestre",
      "Gestão De Segurança Privada", "Gestão De Eventos", "Gestão Desportiva E De Lazer",
      "Gestão Portuária", "Turismo Patrimonial E Socioambiental", "Gestão De Segurança Pública",
      "Artilharia", "Cavalaria", "Comunicações Militares", "Construções Militares", "Infantaria",
      "Estética E Cosmetologia", "Intendência", "Manutenção De Armamento Militar",
      "Manutenção De Comunicações Militares", "Manutenção De Viatura Blindada",
      "Manutenção De Viatura Militar", "Manutenção Metal-Mecânica Militar", "Música Militar",
      "Saúde Militar", "Topografia Militar", "Transporte Aéreo", "Futebol",
      "Gestão De Empreendimentos Gastronômicos", "Manutenção De Aeronave De Asas Rotativas", "Serviços Penais"
    ]
  }
];

export const findCourseInfo = (courseName: string): { area: string; grau: number } | undefined => {
  for (const category of COURSE_CATALOG) {
    if (category.cursos.some(c => c.toLowerCase() === courseName.toLowerCase())) {
      return { area: category.area, grau: category.grau };
    }
  }
  return undefined;
};